resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /toxiproxy/ {
        proxy_pass http://toxiproxy:8474/;
        proxy_set_header Host toxiproxy;
        proxy_set_header User-Agent curl/8.0;
    }

    location /data-gen/ {
        set $data_gen http://data-generator:8888;
        rewrite ^/data-gen/(.*) /$1 break;
        proxy_pass $data_gen;
        proxy_set_header Host data-generator;
    }
}
