server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /toxiproxy/ {
        proxy_pass http://toxiproxy:8474/;
        proxy_set_header Host toxiproxy;
        proxy_set_header User-Agent curl/8.0;
    }
}
