global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gemfire-site-a
    metrics_path: /metrics
    static_configs:
      - targets: ['site-a-server:8080']
        labels:
          site: 'site-a'

  - job_name: gemfire-site-b
    metrics_path: /metrics
    static_configs:
      - targets: ['site-b-server:8080']
        labels:
          site: 'site-b'

  - job_name: toxiproxy
    metrics_path: /metrics
    static_configs:
      - targets: ['toxiproxy:8474']
